name: twitterish
base: core20
version: '2.0.0-beta-1'
summary: Browser Twitter and memes
description: |
  Browser Twitter and memes

architectures:
  - build-on: amd64
    run-on: [amd64]

grade: devel
confinement: devmode

parts:
  my-part:
    plugin: nil
