
  name: twitterr
  version: '2.03' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Browse Twitter.com
  description: |
    Use the mobile Twitter experience from the convenience of a desktop application that works for Windows, macOS, and Linux!

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
    source: https://github.com/KorbsStudio/Twitterr/releases/download/v2.02/Twitterr-Linux.zip
    plugin: autotools
  
