name: twitterish
version: '2.0.0-beta-1'
summary: Browser Twitter and memes
description: |
  Browser Twitter and memes
base: core18
confinement: strict
grade: stable

architectures:
  - build-on: all
    run-on: amd64

apps:
  twitterish:
    command: twitterish/twitterish --no-sandbox
    plugs:
    - browser-support
    - network
    - network-bind
    environment:
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  twitterish:
    plugin: nil
    source: https://github.com/KorbsStudio/twitterish.git
    override-build: |
        npm install electron electron-packager
        npx electron-packager . --overwrite --platform=linux --output=release-build --prune=true
        cp -rv ./twitterish-linux-* $SNAPCRAFT_PART_INSTALL/twitterish
    build-snaps:
    - node/14/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4