name: twitterr
version: '2.031'
summary: Browse Twitter
description: |
Use the mobile Twitter experience from the convenience of a desktop application that works for Windows, macOS, and Linux!
grade: stable
confinement: strict

apps:
  twitterr:
    command: ./twitterr

parts:
  gnu-hello:
    source: https://github.com/KorbsStudio/Twitterr/releases/download/v2.02/Twitterr-Linux.zip
    plugin: autotools